# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 20f0d104515dda875a969b1ea7a8935de883684a1a1a3796fbdb1f6872c33526ed426cfd300149af42bb09578634ee96887165024e72571ce0a5d87b84b47593

test:
  secret_key_base: abf7c34b8bea57ba985f340350d46394108ea7bf723081580f9e720f19a619bab8e386ec6bc0753531fdc94e568ddc7bc29ef6b773a0b7365f8e4936aba8fee9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
